name: PKCiOS
options:
  bundleIdPrefix: com.pborgen
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 7.1.0
targets:
  PKCiOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pborgen.knowledgebase
        INFOPLIST_FILE: Sources/Info.plist
    dependencies:
      - package: GoogleSignIn
products:
  - name: PKCiOS
    type: application
    targets:
      - PKCiOS
